title: Karang Taruna App
description: Web-App Resmi Organisasi Karang Taruna
url: "https://cxllme-ahla.github.io" 
theme: minima # Base theme (akan kita override penuh)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# Default Front Matter  
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
collections:
  agenda:
    output: true
    permalink: /agenda/:path/
