title: "Blog Biru Laut"
description: "Blog responsif dengan desain Material 3"
url: "https://cxllme-ahla.github.io" # Isi dengan URL GitHub Pages Anda nantinya (contoh: https://username.github.io)
plugins:
  - jekyll-paginate

# Pengaturan Pagination
paginate: 5
paginate_path: "/page:num/"
